###############################################################
#  Generated by:      Cadence Innovus 21.18-s099_1
#  OS:                Linux x86_64(Host ID ncdc-0137)
#  Generated on:      Fri Aug  7 06:42:09 2026
#  Design:            counter
#  Command:           write_db counter_routed.db
###############################################################
current_design counter
create_clock [get_ports {clk}]  -name clk -period 10.000000 -waveform {0.000000 5.000000}
set_propagated_clock  [get_ports {clk}]
set_input_transition 0.8  [get_ports {clk}]
set_input_transition 0.8  [get_ports {reset}]
set_load -pin_load -max  0.1  [get_ports {count[3]}]
set_load -pin_load -min  0.1  [get_ports {count[3]}]
set_load -pin_load -max  0.1  [get_ports {count[2]}]
set_load -pin_load -min  0.1  [get_ports {count[2]}]
set_load -pin_load -max  0.1  [get_ports {count[1]}]
set_load -pin_load -min  0.1  [get_ports {count[1]}]
set_load -pin_load -max  0.1  [get_ports {count[0]}]
set_load -pin_load -min  0.1  [get_ports {count[0]}]
set_max_capacitance 0.2  [get_designs {counter}]
set_max_fanout 10  [get_designs {counter}]
set_max_transition 0.5  [get_designs {counter}]
set_input_delay -add_delay 0.15 -min -clock [get_clocks {clk}] [get_ports {reset}]
set_input_delay -add_delay 1 -max -clock [get_clocks {clk}] [get_ports {reset}]
set_output_delay -add_delay 0.15 -min -clock [get_clocks {clk}] [get_ports {count[3]}]
set_output_delay -add_delay 1 -max -clock [get_clocks {clk}] [get_ports {count[3]}]
set_output_delay -add_delay 0.15 -min -clock [get_clocks {clk}] [get_ports {count[1]}]
set_output_delay -add_delay 1 -max -clock [get_clocks {clk}] [get_ports {count[1]}]
set_output_delay -add_delay 0.15 -min -clock [get_clocks {clk}] [get_ports {count[2]}]
set_output_delay -add_delay 1 -max -clock [get_clocks {clk}] [get_ports {count[2]}]
set_output_delay -add_delay 0.15 -min -clock [get_clocks {clk}] [get_ports {count[0]}]
set_output_delay -add_delay 1 -max -clock [get_clocks {clk}] [get_ports {count[0]}]
set_clock_uncertainty 0.05 -hold [get_clocks {clk}]
set_clock_uncertainty 0.15 -setup [get_clocks {clk}]
set_ideal_network  [get_ports {clk}]
set_ideal_network  [get_ports {reset}]
