/*
###############################################################
#  Generated by:      Cadence Innovus 21.18-s099_1
#  OS:                Linux x86_64(Host ID ncdc-0137)
#  Generated on:      Fri Aug  7 05:57:59 2026
#  Design:            counter
#  Command:           write_netlist /home/cc/Documents/Abdullah/Lab01_Materials/Lab01_Data/export/Innovus_Data/outputs/pnr/counter.final.v -exclude_leaf_cells
###############################################################
*/
// Generated by Cadence Genus(TM) Synthesis Solution 21.18-s082_1
// Generated on: Jul 29 2026 05:32:09 EDT (Jul 29 2026 09:32:09 UTC)
// Verification Directory fv/counter 
module counter (
	clk, 
	reset, 
	count);
   input clk;
   input reset;
   output [3:0] count;

   // Internal wires
   wire FE_OFN3_count_0;
   wire FE_OFN2_count_1;
   wire FE_OFN1_count_2;
   wire FE_OFN0_count_3;
   wire n_0;
   wire n_1;
   wire n_2;
   wire n_3;
   wire n_4;
   wire n_5;
   wire n_6;

   CKBD4 FE_OFC3_count_0 (.I(FE_OFN3_count_0),
	.Z(count[0]));
   CKBD4 FE_OFC2_count_1 (.I(FE_OFN2_count_1),
	.Z(count[1]));
   CKBD4 FE_OFC1_count_2 (.I(FE_OFN1_count_2),
	.Z(count[2]));
   CKBD4 FE_OFC0_count_3 (.I(FE_OFN0_count_3),
	.Z(count[3]));
   DFCNQD1 \count_reg[3]  (.CDN(n_5),
	.CP(clk),
	.D(n_6),
	.Q(FE_OFN0_count_3));
   XOR2D1 g81__2398 (.A1(n_3),
	.A2(count[3]),
	.Z(n_6));
   DFCNQD1 \count_reg[2]  (.CDN(n_5),
	.CP(clk),
	.D(n_4),
	.Q(FE_OFN1_count_2));
   HA1D0 g83__5107 (.A(FE_OFN1_count_2),
	.B(n_1),
	.CO(n_3),
	.S(n_4));
   DFCNQD1 \count_reg[1]  (.CDN(n_5),
	.CP(clk),
	.D(n_2),
	.Q(FE_OFN2_count_1));
   HA1D0 g85__6260 (.A(count[0]),
	.B(FE_OFN2_count_1),
	.CO(n_1),
	.S(n_2));
   CKND0 g87 (.I(reset),
	.ZN(n_5));
   DFCND1 \count_reg[0]  (.CDN(n_5),
	.CP(clk),
	.D(n_0),
	.Q(FE_OFN3_count_0),
	.QN(n_0));
endmodule

