###############################################################
#  Generated by:      Cadence Innovus 21.18-s099_1
#  OS:                Linux x86_64(Host ID ncdc-0137)
#  Generated on:      Wed Aug 12 04:39:42 2026
#  Design:            top_wrapper
#  Command:           create_floorplan -core_size {350.0 350.0 20.0 20.0 20.0 20.0} -core_margins_by io -floorplan_origin center -site core -match_to_site -flip s
###############################################################

(globals
    version = 3
    io_order = default
)
(iopad
    (row
	(locals row_name="INIT_corner_E_3")
	(inst  name="CornerCell3"	cell="PCORNER" )
    )
    (row
	(locals row_name="INIT_corner_S_2")
	(inst  name="CornerCell4"	cell="PCORNER" )
    )
    (row
	(locals row_name="INIT_corner_W_1")
	(inst  name="CornerCell1"	cell="PCORNER" )
    )
    (row
	(locals row_name="INIT_corner_N_0")
	(inst  name="CornerCell2"	cell="PCORNER" )
    )
    (row
	(locals row_name="INIT_pad_E_3")
	(inst  name="out_inst7"	)
	(inst  name="out_inst6"	)
	(inst  name="out_inst5"	)
	(inst  name="PVSSR"	cell="PVSS1DGZ" )
	(inst  name="out_inst4"	)
	(inst  name="out_inst3"	)
	(inst  name="out_inst2"	)
	(inst  name="PVDDR"	cell="PVDD1DGZ" )
	(inst  name="out_inst1"	)
	(inst  name="out_inst0"	)
    )
    (row
	(locals row_name="INIT_pad_S_2")
	(inst  name="PVSSB"	cell="PVSS1DGZ" )
	(inst  name="clk_pad"	)
	(inst  name="PVDDB"	cell="PVDD1DGZ" )
    )
    (row
	(locals row_name="INIT_pad_W_1")
	(inst  name="A_inst0"	)
	(inst  name="A_inst1"	)
	(inst  name="A_inst2"	)
	(inst  name="PVDDL"	cell="PVDD1DGZ" )
	(inst  name="A_inst3"	)
	(inst  name="A_inst4"	)
	(inst  name="A_inst5"	)
	(inst  name="PVSSL"	cell="PVSS1DGZ" )
	(inst  name="A_inst6"	)
	(inst  name="A_inst7"	)
	(inst  name="rst_inst"	)
    )
    (row
	(locals row_name="INIT_pad_N_0")
	(inst  name="B_inst0"	)
	(inst  name="B_inst1"	)
	(inst  name="B_inst2"	)
	(inst  name="PVDDT"	cell="PVDD1DGZ" )
	(inst  name="B_inst3"	)
	(inst  name="B_inst4"	)
	(inst  name="B_inst5"	)
	(inst  name="PVSST"	cell="PVSS1DGZ" )
	(inst  name="B_inst6"	)
	(inst  name="B_inst7"	)
	(inst  name="sel_inst0"	)
	(inst  name="sel_inst1"	)
    )
)
