################################################################################
# CADENCE INNOVUS: FLAT PLACE & ROUTE SCRIPT (ANNOTATED & EXPLAINED)
# Design: top_wrapper (ALU with I/O Pads)
# Technology: TSMC 65nm (9-Layer Metal Stack)
# Purpose: Full physical design flow from Netlist to GDSII
################################################################################

# ==============================================================================
# 1. PROJECT VARIABLES & SETUP
# ==============================================================================

# ------------------------------------------------------------------------------
# ⚠️ IMPORTANT: UPDATE THIS DIRECTORY PATH FOR YOUR SPECIFIC PC ⚠️
# ------------------------------------------------------------------------------
# set WORK_DIR: Defines the root workspace directory. All other paths derive from this.
set WORK_DIR                  "/home/cc/Documents/Abdullah/Lab_04_Data"
# ------------------------------------------------------------------------------

# set design(TOPLEVEL): Defines the name of the top module to be used in output files.
set design(TOPLEVEL)          "top_wrapper"

# --- Output Infrastructure & Directory Creation ---
# Define paths for saving Innovus outputs (GDS, Netlists) and reports.
set INNOVUS_DATA_DIR          "${WORK_DIR}/export/Innovus_Data"
set design(export_dir)        "${INNOVUS_DATA_DIR}/outputs"
set design(reports_dir)       "${INNOVUS_DATA_DIR}/reports"

# file mkdir: Instructs the OS to create the folder hierarchy to avoid 'directory not found' errors.
file mkdir $INNOVUS_DATA_DIR \
           ${design(export_dir)}/pnr \
           ${design(reports_dir)}/verify \
           ${design(reports_dir)}/signoff \
           ${design(reports_dir)}/placement \
           ${design(reports_dir)}/opt \
           ${design(reports_dir)}/cts \
           ${design(reports_dir)}/route

# --- Inputs ---
# Link the gate-level netlist generated by the Genus Synthesis tool.
set design(postsyn_netlist)   "${WORK_DIR}/export/Synthesis_Data/netlists/${design(TOPLEVEL)}_physical_synth.v"
# Link the MMMC (Multi-Mode Multi-Corner) file for timing constraints (SDC) and RC corners.
set design(mmmc_view_file)    "${WORK_DIR}/inputs/mmmc_master.view"
# Link the IO file which dictates exact coordinates for input/output pad pins.
set design(io_file)           "${WORK_DIR}/inputs/ALU.io"
# Link the LEF files (Standard Logic Cells + I/O Pad Cells)
set tech(ALL_LEFS)            [list \
                                  "${WORK_DIR}/libraries/lef/tcbn65lp_9lmT2.lef" \
                                  "${WORK_DIR}/libraries/lef/tpzn65lpgv2od3_9lm.lef" \
                              ]

# --- Cell Library Definitions ---
# Map the logical power/ground pins to physical cell references.
set tech(STANDARD_CELL_VDD)   "VDD"
set tech(STANDARD_CELL_GND)   "VSS"
# Specify the cells used at the ends of standard cell rows to prevent well-spacing DRCs.
set tech(ENDCAPS_right)       "DCAP"    
set tech(ENDCAPS_left)        "DCAP"
# Specify cells used to tie logic '1' and logic '0' without connecting directly to PG rails.
set tech(TIEHI)               "TIEH"
set tech(TIELO)               "TIEL"
# Limit the fanout of tie cells so they don't get overloaded.
set tech(TIE_MAX_FANOUT)      10
# List of Decoupling Capacitor and Filler cells to fill empty spaces in the floorplan.
set tech(DECAP)               "DCAP64 DCAP32 DCAP16 DCAP8 DCAP4 DCAP"
set tech(FILLERS)             "FILL64 FILL32 FILL16 FILL8 FILL4 FILL2 FILL1"

# --- Global Net Definitions ---
# Explicitly name the global power and ground nets for routing.
set design(digital_gnd)       "VSS"
set design(digital_vdd)       "VDD"
set design(all_ground_nets)   $design(digital_gnd)
set design(all_power_nets)    $design(digital_vdd)
set design(core_ring_nets)    "$design(digital_gnd) $design(digital_vdd)"


# ==============================================================================
# 2. TOOL SETTINGS & INITIALIZATION
# ==============================================================================
puts "INFO: Starting Stage - Initialization"

# set_library_unit: Sets the base units for time and capacitance for the tool's internal engine.
set_library_unit -time 1ns -cap 1pf
# timing_analysis_type ocv: Enables On-Chip Variation to account for physical manufacturing differences.
set_db timing_analysis_type ocv
# timing_analysis_cppr both: Enables Clock Pessimism Removal for more accurate timing in common clock paths.
set_db timing_analysis_cppr both
# timing_report_unconstrained_paths: Forces the tool to report paths missing SDC constraints.
set_db timing_report_unconstrained_paths true

# init_ground/power_nets: Tells Innovus which nets act as global VDD and VSS before loading the design.
set_db init_ground_nets $design(all_ground_nets)
set_db init_power_nets  $design(all_power_nets)

# Load constraints (MMMC), physical shapes (LEF), IO definitions, and logical gates (Netlist).
read_mmmc $design(mmmc_view_file) 
read_physical -lef $tech(ALL_LEFS)
read_netlist $design(postsyn_netlist)
read_io_file $design(io_file)

# init_design: Compiles all the loaded files to build the physical database in memory.
init_design

# --- Global Net Connections ---
# connect_global_net: Logically maps the VDD/VSS pins of all standard cells to the global VDD/VSS nets.
connect_global_net $design(digital_gnd) -pin $tech(STANDARD_CELL_GND) -all -verbose
connect_global_net $design(digital_vdd) -pin $tech(STANDARD_CELL_VDD) -all -verbose
# The '-type tie_hi/lo' flags ensure that any logic mapped directly to 1'b1 or 1'b0 in RTL connects to PG rails.
connect_global_net $design(digital_vdd) -type tiehi -all -verbose
connect_global_net $design(digital_gnd) -type tielo -all -verbose


# ==============================================================================
# 3. FLOORPLANNING & I/O PAD INTEGRATION
# ==============================================================================
puts "INFO: Starting Stage - Floorplanning"

# Enable IO flow routing flag
set_io_flow_flag 1

# create_floorplan: Initializes the chip boundary containing Pad cells and the inner core.
# -core_margins_by io: Spacing is calculated relative to the IO pads.
# -core_size: {Width Height Left Bottom Right Top} sets precise constraints.
create_floorplan -core_size {350.0 350.0 20.0 20.0 20.0 20.0} \
                 -core_margins_by io \
                 -floorplan_origin center \
                 -site core \
                 -match_to_site \
                 -flip s

# Route the Pad Ring structure (Provides continuous power around the IO boundary)
route_special -connect {pad_ring} -nets "$design(digital_gnd) $design(digital_vdd)"


# ==============================================================================
# 4. POWER PLANNING (PNS)
# ==============================================================================
puts "INFO: Starting Stage - Power Planning"

# Dynamically fetch the names of the metal layers from the loaded LEF database.
set m6_name [get_db [lindex [get_db layers] 6] .name]
set m7_name [get_db [lindex [get_db layers] 7] .name]

# --- 4.1 Core Power Rings ---
# RINGS CONFIGURATION:
# - Using M6 (Vertical) and M7 (Horizontal) for macro-level rings. 
# - Ring width is set to 5.4um for optimal Electromigration (EM) and IR Drop limits.
add_rings -type core_rings \
          -nets $design(core_ring_nets) \
          -follow core \
          -layer "top $m7_name bottom $m7_name left $m6_name right $m6_name" \
          -width 5.4 \
          -spacing 3.6 \
          -offset 0.9 \
          -center 1 \
          -threshold 0 \
          -jog_distance 0 \
          -snap_wire_center_to_grid none

puts "INFO: Core Rings Created Successfully on M6/M7!"

# --- 4.2 Power Routing (Follow Pins to Core/Pad Rings) ---
set_db route_special_via_connect_to_shape { stripe }

# Route Standard Cell internal power pins to the nearest available power structure
route_special -nets { VDD VSS } \
              -connect {block_pin core_pin floating_stripe} \
              -layer_change_range { M1(1) M9(9) } \
              -block_pin_target nearest_target \
              -core_pin_target first_after_row_end \
              -floating_stripe_target {block_ring pad_ring ring stripe ring_pin block_pin followpin} \
              -core_pin_check_stdcell_geometry \
              -allow_jogging 1 \
              -crossover_via_layer_range { M1(1) M9(9) } \
              -allow_layer_change 1 \
              -block_pin use_lef \
              -target_via_layer_range { M1(1) M9(9) }

# Route the external IO Pad Pins specifically to the pad ring
route_special -nets { VDD VSS } \
              -connect {pad_pin pad_ring floating_stripe} \
              -layer_change_range { M4(4) M9(9) } \
              -block_pin_target nearest_target \
              -pad_pin_port_connect {all_port one_geom} \
              -pad_pin_target nearest_target \
              -floating_stripe_target {block_ring pad_ring ring stripe ring_pin block_pin followpin} \
              -core_pin_check_stdcell_geometry \
              -allow_jogging 1 \
              -crossover_via_layer_range { M4(4) M9(9) } \
              -allow_layer_change 1 \
              -target_via_layer_range { M4(4) M9(9) }

puts "INFO: Standard Cell and IO Pad Power Routing Completed Successfully!"

# --- 4.3 Endcaps & Vertical Power Stripes ---
# Ensure standard cell row ends are sealed properly with DCAP isolation boundaries
set_db add_endcaps_right_edge $tech(ENDCAPS_right)
set_db add_endcaps_left_edge  $tech(ENDCAPS_left)
add_endcaps -prefix ENDCAP

# Creates vertical power meshes across the core to distribute power evenly.
add_stripes -nets "$design(digital_gnd) $design(digital_vdd)" \
            -direction vertical \
            -layer M4 \
            -width 0.9 \
            -spacing 0.8 \
            -set_to_set_distance 4.6 \
            -start_from left \
            -start_offset 0.9

puts "INFO: Vertical Power Stripes Generated Successfully on M4!"


# ==============================================================================
# 5. PLACEMENT
# ==============================================================================
puts "INFO: Starting Stage - Placement"

# place_global_cong_effort auto: Tells the placer to automatically resolve routing congestion.
set_db place_global_cong_effort auto
set_db place_global_max_density 0.2

# place_opt_design: The core placement engine. Places standard cells and does initial timing optimization.
place_opt_design -report_dir "$design(reports_dir)/placement/place_opt_design"

# check_place: Verifies there are no overlapping cells or placement violations.
check_place

# delete_routes: Cleans up any trial routing lines generated during placement optimization.
delete_routes -type regular 

# Tie-off Insertion: Replaces direct logical 1/0 connections with actual physical cells.
set_db add_tieoffs_prefix "TIE"
set_db add_tieoffs_cells "$tech(TIEHI) $tech(TIELO)"
set_db add_tieoffs_max_fanout $tech(TIE_MAX_FANOUT)
add_tieoffs

# opt_design -pre_cts: Runs a timing optimization pass focusing purely on Setup Time and Max Trans/Cap (DRVs).
opt_design -pre_cts -drv -setup -report_dir "$design(reports_dir)/opt/pre_cts"

# write_netlist: Saves a checkpoint snapshot of the placed design.
write_netlist ${design(export_dir)}/pnr/${design(TOPLEVEL)}_placed.v


# ==============================================================================
# 6. CLOCK TREE SYNTHESIS (CTS)
# ==============================================================================
puts "INFO: Starting Stage - Clock Tree Synthesis"

# create_clock_tree_spec: Extracts clock definitions from the SDC and builds routing rules.
create_clock_tree_spec

# ccopt_design: Clock Concurrent Optimization. Builds the physical clock tree, balances skew, and routes clock nets.
ccopt_design -report_dir "$design(reports_dir)/cts/ccopt_design"

# opt_design -post_cts: Now that real clocks exist, fix any newly introduced Setup/Hold or DRV violations.
opt_design -post_cts -setup -hold -drv -report_dir "$design(reports_dir)/opt/post_cts"
write_netlist ${design(export_dir)}/pnr/${design(TOPLEVEL)}_cts.v


# ==============================================================================
# 7. ROUTING
# ==============================================================================
puts "INFO: Starting Stage - Detailed Routing"

# Enable Signal Integrity (Crosstalk) and Timing-driven routing rules.
set_db delaycal_enable_si true
set_db route_design_with_timing_driven true
set_db route_design_with_si_driven true
set_db route_design_with_eco true

# route_opt_design: The main NanoRoute engine. Physically connects all data pins using actual metal layers.
route_opt_design

# opt_design -post_route: Fixes Setup/Hold violations using accurate, post-route RC delays.
opt_design -post_route -setup -hold -drv -report_dir "$design(reports_dir)/opt/post_route"
write_netlist ${design(export_dir)}/pnr/${design(TOPLEVEL)}_routed.v


# ==============================================================================
# 8. DESIGN FOR MANUFACTURING (DFM)
# ==============================================================================
puts "INFO: Starting Stage - DFM Optimizations"

# Temporarily disable timing/SI constraints to focus purely on yield improvements.
set_db route_design_with_timing_driven false
set_db route_design_with_si_driven false
set_db route_design_with_eco false

# Spread wires apart and add multiple cuts to vias to reduce the chance of manufacturing defects.
set_db route_design_detail_post_route_spread_wire true
set_db route_design_detail_use_multi_cut_via_effort high

# Execute via optimization and wire optimization.
route_design -via_opt
route_design -wire_opt

# Restore the timing/SI constraints back to normal.
set_db route_design_detail_post_route_spread_wire false
set_db route_design_with_timing_driven true
set_db route_design_with_si_driven true
set_db route_design_with_eco true


# ==============================================================================
# 9. PHYSICAL CONTINUITY (FILLER INSERTION)
# ==============================================================================
puts "INFO: Starting Stage - Filler Insertion"

# add_fillers: Fills all remaining empty space in the core with decoupling caps and dummy fillers.
set_db add_fillers_prefix FILLDECAP
set_db add_fillers_cells [concat $tech(DECAP) $tech(FILLERS)]
add_fillers

# route_eco -fix_drc: Fixes any minor Design Rule Check (DRC) violations introduced by inserting fillers.
route_eco -fix_drc

edit_trim_routes -all       
delete_empty_hinst          


# ==============================================================================
# 10. VERIFICATION & POWER ANALYSIS
# ==============================================================================
puts "INFO: Starting Stage - Verification"

# check_drc: Validates the layout against TSMC physical manufacturing rules.
check_drc -out_file "$design(reports_dir)/verify/drc_violations.rpt"

# check_connectivity: Ensures no open nets, shorts, or floating pins exist.
check_connectivity -type all -out_file "$design(reports_dir)/verify/connectivity.rpt"

# --- Vectorless Power Estimation ---
# Resets the power engine, defines an assumed 20% toggle rate, and generates a static power report.
set_power_output_dir -reset
set_default_switching_activity -reset
set_power -reset
set_power_output_dir ./
set_default_switching_activity -input_activity 0.2 -period 10.0
report_power -rail_analysis_format VS -out_file "$design(reports_dir)/verify/power_report.rpt"


# ==============================================================================
# 11. SIGNOFF STA (TEMPUS)
# ==============================================================================
puts "INFO: Starting Stage - Signoff Timing"

# time_design: Uses the integrated Tempus engine for final, highly accurate Sign-off Static Timing Analysis.
set_analysis_view -setup {view_func_setup} -hold {view_func_hold}
time_design -post_route -report_dir $design(reports_dir)/signoff/setup
time_design -post_route -hold -report_dir $design(reports_dir)/signoff/hold


# ==============================================================================
# 12. FINAL EXPORT (HANDOFF)
# ==============================================================================
puts "INFO: Starting Stage - Data Export"

# write_netlist: Exports the final post-route Verilog netlist (excluding physical-only filler cells).
write_netlist ${design(export_dir)}/pnr/${design(TOPLEVEL)}.final.v -exclude_leaf_cells

# extract_rc / write_parasitics: Extracts final Resistance and Capacitance data into a SPEF file for external STA.
set_db extract_rc_coupled true
extract_rc
write_parasitics -spef_file ${design(export_dir)}/pnr/${design(TOPLEVEL)}.spef

# 1. Export Macro LEF (Abstract View for Top-Level Physical Routing)
# -stripe_pins ensures power rings are exported as connectable pins for top-level.
write_lef_abstract ${design(export_dir)}/pnr/${design(TOPLEVEL)}_macro.lef -stripe_pins

# Corrected macro timing model extraction with valid MMMC setup and view definition
set_analysis_view -setup {view_func_setup} -hold {view_func_setup}
write_timing_model ${design(export_dir)}/pnr/${design(TOPLEVEL)}_macro.lib -view view_func_setup

# Save routed database checkpoint for future use
write_db ${design(export_dir)}/pnr/${design(TOPLEVEL)}_routed_final.db

# ------------------------------------------------------------------------------
# --- FIXED: Corrected paths for GDS merge and Map files based on tree logic ---
# ------------------------------------------------------------------------------
# write_stream: Generates the ultimate GDSII mask layout file to send to the fabrication foundry (TSMC).
write_stream ${design(export_dir)}/pnr/${design(TOPLEVEL)}.gds \
  -unit 1000 \
  -mode ALL \
  -merge "${WORK_DIR}/libraries/gds/tcbn65lp.gds /home/cc/Documents/Abdullah/Lab_04_Data/libraries/gds/tpzn65lpgv2od3.gds" \
  -map_file "${WORK_DIR}/libraries/map/PRTF_EDI_N65_gdsout_6X1Z1U.24a.map" 

puts "INFO: Place and Route Flow Completed Successfully!"
gui_fit
