#==============================================================================
# Hierarchical dofile generated by Conformal LEC
# Version: 23.10-s300 (30-Aug-2023) (64 bit executable)
#------------------------------------------------------------------------------
# Hierarchical dofile is generated by following configuration:
# write_hier_compare_dofile
#     -NOExact_pin_match
#     -Constraints
#     -INPUT_OUTPUT_Pin_equivalence
#     -BALANCED_EXTractions
#     -PREPEND_String 'report_design_data; report_unmapped_points -summary; report_unmapped_points -notmapped; analyze_datapath -module -verbose; eval analyze_datapath -flowgraph -verbose'
#     -Usage
#     -Replace
#     -VERbose
#     'hier_tmp2.lec.do'
#------------------------------------------------------------------------------
# For additional reporting on 'not written' modules, see the 'VERBOSE REPORTING'
# section at the end of the hierarchical dofile
#------------------------------------------------------------------------------
# The command 'set module property' sets the instance context for the current
# root module. It is intended only for hierarchical comparison, and should
# not be modified by the user.
#------------------------------------------------------------------------------
# TERMS AND NOTATIONS USED
#------------------------------------------------------------------------------
# Module Instantiation Ratio: Average number of instantiations per matching module
# Wrapper size: Logic gates enclosing the module's instance, and bounded by key-points
# Periphery size: Logic gates in the fanin and fanout cone of instance's input and output boundary, and bounded by key-points
# 0: Indicates pin is constant zero
# 1: Indicates pin is constant one
# X: Indicates pin is full DC
# U: Indicates pin is unreachable
# Z: Indicates pin is floating
# KP<--: Indicates pin's fanin is directly connected to key-point (ignores buffers/inverters)
# -->KP: Indicates pin's fanout is directly connected to key-point (ignores buffers/inverters)
# REP: Indicates pin is representative pin
# EQ_REP: <polarity> rep_pinname>: Indicates pin is a member EQ pin with
# 'rep_pinname' specifying the representative, and 'polarity' specifying
# if it is positive or negative equivalent
# = : Indicates that the pins on LHS and RHS are mapped
# + : Indicates positive polarity for pin mapping
# - : Indicates negative polarity for pin mapping
# ? : Indicates unknown polarity for pin mapping
# G: Indicates that the pin belongs to Golden
# R: Indicates that the pin belongs to Revised
# IN: Indicates that the pin is an Input pin
# OUT: Indicates that the pin is an Output pin
# IO: Indicates that the pin is an Inout pin. Polarity of Inout pin is
#     always '?' because of name-only mapping
#==============================================================================

set_system_mode setup
# Root Modules
# Comparing
#-------------------------------------------------------------------------------
# MODULE riscv_core (G) INSTANCE / (G)
# MODULE riscv_core (R) INSTANCE / (R)
# Wrapper size: (G) = 0  (R) = 0
# Periphery size: (G) = 0  (R) = 0
#-------------------------------------------------------------------------------
# RESOLVED Constraints
# IN (G) rst (REP)  =   (R) rst (REP) (by name)
# IN (G) clk (REP)  =   (R) clk (REP) (by name)
# IN (G) instruction[31] (REP)  =   (R) instruction[31] (REP) (by name)
# IN (G) instruction[30] (REP)  =   (R) instruction[30] (REP) (by name)
# IN (G) instruction[29] (REP)  =   (R) instruction[29] (REP) (by name)
# IN (G) instruction[28] (REP)  =   (R) instruction[28] (REP) (by name)
# IN (G) instruction[27] (REP)  =   (R) instruction[27] (REP) (by name)
# IN (G) instruction[26] (REP)  =   (R) instruction[26] (REP) (by name)
# IN (G) instruction[25] (REP)  =   (R) instruction[25] (REP) (by name)
# IN (G) instruction[24] (REP)  =   (R) instruction[24] (REP) (by name)
# IN (G) instruction[23] (REP)  =   (R) instruction[23] (REP) (by name)
# IN (G) instruction[22] (REP)  =   (R) instruction[22] (REP) (by name)
# IN (G) instruction[21] (REP)  =   (R) instruction[21] (REP) (by name)
# IN (G) instruction[20] (REP)  =   (R) instruction[20] (REP) (by name)
# IN (G) instruction[19] (REP)  =   (R) instruction[19] (REP) (by name)
# IN (G) instruction[18] (REP)  =   (R) instruction[18] (REP) (by name)
# IN (G) instruction[17] (REP)  =   (R) instruction[17] (REP) (by name)
# IN (G) instruction[16] (REP)  =   (R) instruction[16] (REP) (by name)
# IN (G) instruction[15] (REP)  =   (R) instruction[15] (REP) (by name)
# IN (G) instruction[14] (REP)  =   (R) instruction[14] (REP) (by name)
# IN (G) instruction[13] (REP)  =   (R) instruction[13] (REP) (by name)
# IN (G) instruction[12] (REP)  =   (R) instruction[12] (REP) (by name)
# IN (G) instruction[11] (REP)  =   (R) instruction[11] (REP) (by name)
# IN (G) instruction[10] (REP)  =   (R) instruction[10] (REP) (by name)
# IN (G) instruction[9] (REP)  =   (R) instruction[9] (REP) (by name)
# IN (G) instruction[8] (REP)  =   (R) instruction[8] (REP) (by name)
# IN (G) instruction[7] (REP)  =   (R) instruction[7] (REP) (by name)
# IN (G) instruction[6] (REP)  =   (R) instruction[6] (REP) (by name)
# IN (G) instruction[5] (REP)  =   (R) instruction[5] (REP) (by name)
# IN (G) instruction[4] (REP)  =   (R) instruction[4] (REP) (by name)
# IN (G) instruction[3] (REP)  =   (R) instruction[3] (REP) (by name)
# IN (G) instruction[2] (REP)  =   (R) instruction[2] (REP) (by name)
# IN (G) instruction[1] (REP)  =   (R) instruction[1] (REP) (by name)
# IN (G) instruction[0] (REP)  =   (R) instruction[0] (REP) (by name)
# IN (G) raw_dmem_read[31] (REP)  =   (R) raw_dmem_read[31] (REP) (by name)
# IN (G) raw_dmem_read[30] (REP)  =   (R) raw_dmem_read[30] (REP) (by name)
# IN (G) raw_dmem_read[29] (REP)  =   (R) raw_dmem_read[29] (REP) (by name)
# IN (G) raw_dmem_read[28] (REP)  =   (R) raw_dmem_read[28] (REP) (by name)
# IN (G) raw_dmem_read[27] (REP)  =   (R) raw_dmem_read[27] (REP) (by name)
# IN (G) raw_dmem_read[26] (REP)  =   (R) raw_dmem_read[26] (REP) (by name)
# IN (G) raw_dmem_read[25] (REP)  =   (R) raw_dmem_read[25] (REP) (by name)
# IN (G) raw_dmem_read[24] (REP)  =   (R) raw_dmem_read[24] (REP) (by name)
# IN (G) raw_dmem_read[23] (REP)  =   (R) raw_dmem_read[23] (REP) (by name)
# IN (G) raw_dmem_read[22] (REP)  =   (R) raw_dmem_read[22] (REP) (by name)
# IN (G) raw_dmem_read[21] (REP)  =   (R) raw_dmem_read[21] (REP) (by name)
# IN (G) raw_dmem_read[20] (REP)  =   (R) raw_dmem_read[20] (REP) (by name)
# IN (G) raw_dmem_read[19] (REP)  =   (R) raw_dmem_read[19] (REP) (by name)
# IN (G) raw_dmem_read[18] (REP)  =   (R) raw_dmem_read[18] (REP) (by name)
# IN (G) raw_dmem_read[17] (REP)  =   (R) raw_dmem_read[17] (REP) (by name)
# IN (G) raw_dmem_read[16] (REP)  =   (R) raw_dmem_read[16] (REP) (by name)
# IN (G) raw_dmem_read[15] (REP)  =   (R) raw_dmem_read[15] (REP) (by name)
# IN (G) raw_dmem_read[14] (REP)  =   (R) raw_dmem_read[14] (REP) (by name)
# IN (G) raw_dmem_read[13] (REP)  =   (R) raw_dmem_read[13] (REP) (by name)
# IN (G) raw_dmem_read[12] (REP)  =   (R) raw_dmem_read[12] (REP) (by name)
# IN (G) raw_dmem_read[11] (REP)  =   (R) raw_dmem_read[11] (REP) (by name)
# IN (G) raw_dmem_read[10] (REP)  =   (R) raw_dmem_read[10] (REP) (by name)
# IN (G) raw_dmem_read[9] (REP)  =   (R) raw_dmem_read[9] (REP) (by name)
# IN (G) raw_dmem_read[8] (REP)  =   (R) raw_dmem_read[8] (REP) (by name)
# IN (G) raw_dmem_read[7] (REP)  =   (R) raw_dmem_read[7] (REP) (by name)
# IN (G) raw_dmem_read[6] (REP)  =   (R) raw_dmem_read[6] (REP) (by name)
# IN (G) raw_dmem_read[5] (REP)  =   (R) raw_dmem_read[5] (REP) (by name)
# IN (G) raw_dmem_read[4] (REP)  =   (R) raw_dmem_read[4] (REP) (by name)
# IN (G) raw_dmem_read[3] (REP)  =   (R) raw_dmem_read[3] (REP) (by name)
# IN (G) raw_dmem_read[2] (REP)  =   (R) raw_dmem_read[2] (REP) (by name)
# IN (G) raw_dmem_read[1] (REP)  =   (R) raw_dmem_read[1] (REP) (by name)
# IN (G) raw_dmem_read[0] (REP)  =   (R) raw_dmem_read[0] (REP) (by name)
# RESOLVED Constraints
# OUT (G) pc_current[31] (REP)  =   (R) pc_current[31] (REP) (by name)
# OUT (G) pc_current[30] (REP)  =   (R) pc_current[30] (REP) (by name)
# OUT (G) pc_current[29] (REP)  =   (R) pc_current[29] (REP) (by name)
# OUT (G) pc_current[28] (REP)  =   (R) pc_current[28] (REP) (by name)
# OUT (G) pc_current[27] (REP)  =   (R) pc_current[27] (REP) (by name)
# OUT (G) pc_current[26] (REP)  =   (R) pc_current[26] (REP) (by name)
# OUT (G) pc_current[25] (REP)  =   (R) pc_current[25] (REP) (by name)
# OUT (G) pc_current[24] (REP)  =   (R) pc_current[24] (REP) (by name)
# OUT (G) pc_current[23] (REP)  =   (R) pc_current[23] (REP) (by name)
# OUT (G) pc_current[22] (REP)  =   (R) pc_current[22] (REP) (by name)
# OUT (G) pc_current[21] (REP)  =   (R) pc_current[21] (REP) (by name)
# OUT (G) pc_current[20] (REP)  =   (R) pc_current[20] (REP) (by name)
# OUT (G) pc_current[19] (REP)  =   (R) pc_current[19] (REP) (by name)
# OUT (G) pc_current[18] (REP)  =   (R) pc_current[18] (REP) (by name)
# OUT (G) pc_current[17] (REP)  =   (R) pc_current[17] (REP) (by name)
# OUT (G) pc_current[16] (REP)  =   (R) pc_current[16] (REP) (by name)
# OUT (G) pc_current[15] (REP)  =   (R) pc_current[15] (REP) (by name)
# OUT (G) pc_current[14] (REP)  =   (R) pc_current[14] (REP) (by name)
# OUT (G) pc_current[13] (REP)  =   (R) pc_current[13] (REP) (by name)
# OUT (G) pc_current[12] (REP)  =   (R) pc_current[12] (REP) (by name)
# OUT (G) pc_current[11] (REP)  =   (R) pc_current[11] (REP) (by name)
# OUT (G) pc_current[10] (REP)  =   (R) pc_current[10] (REP) (by name)
# OUT (G) pc_current[9] (REP)  =   (R) pc_current[9] (REP) (by name)
# OUT (G) pc_current[8] (REP)  =   (R) pc_current[8] (REP) (by name)
# OUT (G) pc_current[7] (REP)  =   (R) pc_current[7] (REP) (by name)
# OUT (G) pc_current[6] (REP)  =   (R) pc_current[6] (REP) (by name)
# OUT (G) pc_current[5] (REP)  =   (R) pc_current[5] (REP) (by name)
# OUT (G) pc_current[4] (REP)  =   (R) pc_current[4] (REP) (by name)
# OUT (G) pc_current[3] (REP)  =   (R) pc_current[3] (REP) (by name)
# OUT (G) pc_current[2] (REP)  =   (R) pc_current[2] (REP) (by name)
# OUT (G) pc_current[1] (REP)  =   (R) pc_current[1] (REP) (by name)
# OUT (G) pc_current[0] (REP)  =   (R) pc_current[0] (REP) (by name)
# OUT (G) alu_result[31] (REP)  =   (R) alu_result[31] (REP) (by name)
# OUT (G) alu_result[30] (REP)  =   (R) alu_result[30] (REP) (by name)
# OUT (G) alu_result[29] (REP)  =   (R) alu_result[29] (REP) (by name)
# OUT (G) alu_result[28] (REP)  =   (R) alu_result[28] (REP) (by name)
# OUT (G) alu_result[27] (REP)  =   (R) alu_result[27] (REP) (by name)
# OUT (G) alu_result[26] (REP)  =   (R) alu_result[26] (REP) (by name)
# OUT (G) alu_result[25] (REP)  =   (R) alu_result[25] (REP) (by name)
# OUT (G) alu_result[24] (REP)  =   (R) alu_result[24] (REP) (by name)
# OUT (G) alu_result[23] (REP)  =   (R) alu_result[23] (REP) (by name)
# OUT (G) alu_result[22] (REP)  =   (R) alu_result[22] (REP) (by name)
# OUT (G) alu_result[21] (REP)  =   (R) alu_result[21] (REP) (by name)
# OUT (G) alu_result[20] (REP)  =   (R) alu_result[20] (REP) (by name)
# OUT (G) alu_result[19] (REP)  =   (R) alu_result[19] (REP) (by name)
# OUT (G) alu_result[18] (REP)  =   (R) alu_result[18] (REP) (by name)
# OUT (G) alu_result[17] (REP)  =   (R) alu_result[17] (REP) (by name)
# OUT (G) alu_result[16] (REP)  =   (R) alu_result[16] (REP) (by name)
# OUT (G) alu_result[15] (REP)  =   (R) alu_result[15] (REP) (by name)
# OUT (G) alu_result[14] (REP)  =   (R) alu_result[14] (REP) (by name)
# OUT (G) alu_result[13] (REP)  =   (R) alu_result[13] (REP) (by name)
# OUT (G) alu_result[12] (REP)  =   (R) alu_result[12] (REP) (by name)
# OUT (G) alu_result[11] (REP)  =   (R) alu_result[11] (REP) (by name)
# OUT (G) alu_result[10] (REP)  =   (R) alu_result[10] (REP) (by name)
# OUT (G) alu_result[9] (REP)  =   (R) alu_result[9] (REP) (by name)
# OUT (G) alu_result[8] (REP)  =   (R) alu_result[8] (REP) (by name)
# OUT (G) alu_result[7] (REP)  =   (R) alu_result[7] (REP) (by name)
# OUT (G) alu_result[6] (REP)  =   (R) alu_result[6] (REP) (by name)
# OUT (G) alu_result[5] (REP)  =   (R) alu_result[5] (REP) (by name)
# OUT (G) alu_result[4] (REP)  =   (R) alu_result[4] (REP) (by name)
# OUT (G) alu_result[3] (REP)  =   (R) alu_result[3] (REP) (by name)
# OUT (G) alu_result[2] (REP)  =   (R) alu_result[2] (REP) (by name)
# OUT (G) alu_result[1] (REP)  =   (R) alu_result[1] (REP) (by name)
# OUT (G) alu_result[0] (REP)  =   (R) alu_result[0] (REP) (by name)
# OUT (G) formatted_dmem_write[31] (REP)  =   (R) formatted_dmem_write[31] (REP) (by name)
# OUT (G) formatted_dmem_write[30] (REP)  =   (R) formatted_dmem_write[30] (REP) (by name)
# OUT (G) formatted_dmem_write[29] (REP)  =   (R) formatted_dmem_write[29] (REP) (by name)
# OUT (G) formatted_dmem_write[28] (REP)  =   (R) formatted_dmem_write[28] (REP) (by name)
# OUT (G) formatted_dmem_write[27] (REP)  =   (R) formatted_dmem_write[27] (REP) (by name)
# OUT (G) formatted_dmem_write[26] (REP)  =   (R) formatted_dmem_write[26] (REP) (by name)
# OUT (G) formatted_dmem_write[25] (REP)  =   (R) formatted_dmem_write[25] (REP) (by name)
# OUT (G) formatted_dmem_write[24] (REP)  =   (R) formatted_dmem_write[24] (REP) (by name)
# OUT (G) formatted_dmem_write[23] (REP)  =   (R) formatted_dmem_write[23] (REP) (by name)
# OUT (G) formatted_dmem_write[22] (REP)  =   (R) formatted_dmem_write[22] (REP) (by name)
# OUT (G) formatted_dmem_write[21] (REP)  =   (R) formatted_dmem_write[21] (REP) (by name)
# OUT (G) formatted_dmem_write[20] (REP)  =   (R) formatted_dmem_write[20] (REP) (by name)
# OUT (G) formatted_dmem_write[19] (REP)  =   (R) formatted_dmem_write[19] (REP) (by name)
# OUT (G) formatted_dmem_write[18] (REP)  =   (R) formatted_dmem_write[18] (REP) (by name)
# OUT (G) formatted_dmem_write[17] (REP)  =   (R) formatted_dmem_write[17] (REP) (by name)
# OUT (G) formatted_dmem_write[16] (REP)  =   (R) formatted_dmem_write[16] (REP) (by name)
# OUT (G) formatted_dmem_write[15] (REP)  =   (R) formatted_dmem_write[15] (REP) (by name)
# OUT (G) formatted_dmem_write[14] (REP)  =   (R) formatted_dmem_write[14] (REP) (by name)
# OUT (G) formatted_dmem_write[13] (REP)  =   (R) formatted_dmem_write[13] (REP) (by name)
# OUT (G) formatted_dmem_write[12] (REP)  =   (R) formatted_dmem_write[12] (REP) (by name)
# OUT (G) formatted_dmem_write[11] (REP)  =   (R) formatted_dmem_write[11] (REP) (by name)
# OUT (G) formatted_dmem_write[10] (REP)  =   (R) formatted_dmem_write[10] (REP) (by name)
# OUT (G) formatted_dmem_write[9] (REP)  =   (R) formatted_dmem_write[9] (REP) (by name)
# OUT (G) formatted_dmem_write[8] (REP)  =   (R) formatted_dmem_write[8] (REP) (by name)
# OUT (G) formatted_dmem_write[7] (REP)  =   (R) formatted_dmem_write[7] (REP) (by name)
# OUT (G) formatted_dmem_write[6] (REP)  =   (R) formatted_dmem_write[6] (REP) (by name)
# OUT (G) formatted_dmem_write[5] (REP)  =   (R) formatted_dmem_write[5] (REP) (by name)
# OUT (G) formatted_dmem_write[4] (REP)  =   (R) formatted_dmem_write[4] (REP) (by name)
# OUT (G) formatted_dmem_write[3] (REP)  =   (R) formatted_dmem_write[3] (REP) (by name)
# OUT (G) formatted_dmem_write[2] (REP)  =   (R) formatted_dmem_write[2] (REP) (by name)
# OUT (G) formatted_dmem_write[1] (REP)  =   (R) formatted_dmem_write[1] (REP) (by name)
# OUT (G) formatted_dmem_write[0] (REP)  =   (R) formatted_dmem_write[0] (REP) (by name)
# OUT (G) dmem_write_mask[3] (REP)  =   (R) dmem_write_mask[3] (REP) (by name)
# OUT (G) dmem_write_mask[2] (REP)  =   (R) dmem_write_mask[2] (REP) (by name)
# OUT (G) dmem_write_mask[1] (REP)  =   (R) dmem_write_mask[1] (REP) (by name)
# OUT (G) dmem_write_mask[0] (REP)  =   (R) dmem_write_mask[0] (REP) (by name)
# OUT (G) mem_read (REP)  =   (R) mem_read (REP) (by name)
# OUT (G) mem_write (REP)  =   (R) mem_write (REP) (by name)
set_root_module riscv_core -Golden
set_root_module riscv_core -Revised
set_module_property -instance / -Golden
set_module_property -instance / -Revised
report_black_box -NOHidden
set_system_mode lec
report_design_data; report_unmapped_points -summary; report_unmapped_points -notmapped; analyze_datapath -module -verbose; eval analyze_datapath -flowgraph -verbose
add_compared_points -all
compare
save_hier_compare_result
set_system_mode setup
usage
report_hier_compare_result
report_hier_compare_result -Nonequivalent
report_hier_compare_result -Abort
report_hier_compare_result -Uncompared
#-------------------------------------------------------------------------------
# VERBOSE REPORTING
#-------------------------------------------------------------------------------
# The following Golden modules are not written because of non-matching
# instance names in Revised:
# data_mem_ctrl (Instance: data_mem_ctrl_inst) (G)
# reg_file (Instance: reg_file_inst) (G)
# imm_gen (Instance: imm_gen_inst) (G)
# main_ctrl (Instance: main_ctrl_inst) (G)
# alu_ctrl (Instance: alu_ctrl_inst) (G)
# alu (Instance: alu_inst) (G)
#-------------------------------------------------------------------------------
# The following Revised modules are not written because of non-matching
# instance names in Golden:
# csa_tree_alu_inst_eq_34_31_group_4 (Instance: csa_tree_alu_inst_eq_34_31_groupi) (R)
#-------------------------------------------------------------------------------
# _END_OF_LEC_HIERARCHICAL_DOFILE_
