
// Generated by Cadence Genus(TM) Synthesis Solution 21.18-s082_1
// Generated on: Aug  3 2026 05:07:26 EDT (Aug  3 2026 09:07:26 UTC)

// Verification Directory fv/riscv_top 

module riscv_top(rst, clk, pc_current, alu_result,
     formatted_dmem_write, dmem_write_mask, mem_read, mem_write,
     raw_dmem_read);
  input rst, clk;
  output [31:0] pc_current, alu_result, formatted_dmem_write,
       raw_dmem_read;
  output [3:0] dmem_write_mask;
  output mem_read, mem_write;
  wire rst, clk;
  wire [31:0] pc_current, alu_result, formatted_dmem_write,
       raw_dmem_read;
  wire [3:0] dmem_write_mask;
  wire mem_read, mem_write;
  wire [31:0] riscv_core_inst_pc_next;
  wire n_0, n_1, riscv_core_inst_add_57_83_n_872,
       riscv_core_inst_add_57_83_n_876,
       riscv_core_inst_add_57_83_n_880,
       riscv_core_inst_add_57_83_n_882,
       riscv_core_inst_add_57_83_n_885, riscv_core_inst_add_57_83_n_887;
  wire riscv_core_inst_add_57_83_n_889,
       riscv_core_inst_add_57_83_n_892,
       riscv_core_inst_add_57_83_n_894,
       riscv_core_inst_add_57_83_n_896,
       riscv_core_inst_add_57_83_n_898,
       riscv_core_inst_add_57_83_n_899,
       riscv_core_inst_add_57_83_n_904, riscv_core_inst_add_57_83_n_906;
  wire riscv_core_inst_add_57_83_n_907,
       riscv_core_inst_add_57_83_n_910,
       riscv_core_inst_add_57_83_n_912,
       riscv_core_inst_add_57_83_n_914,
       riscv_core_inst_add_57_83_n_916,
       riscv_core_inst_add_57_83_n_918,
       riscv_core_inst_add_57_83_n_919, riscv_core_inst_add_57_83_n_921;
  wire riscv_core_inst_add_57_83_n_926,
       riscv_core_inst_add_57_83_n_927,
       riscv_core_inst_add_57_83_n_928,
       riscv_core_inst_add_57_83_n_933,
       riscv_core_inst_add_57_83_n_935,
       riscv_core_inst_add_57_83_n_937,
       riscv_core_inst_add_57_83_n_941, riscv_core_inst_add_57_83_n_943;
  wire riscv_core_inst_add_57_83_n_948,
       riscv_core_inst_add_57_83_n_953,
       riscv_core_inst_add_57_83_n_958, riscv_core_inst_add_57_83_n_963;
  assign raw_dmem_read[0] = 1'b0;
  assign raw_dmem_read[1] = 1'b0;
  assign raw_dmem_read[2] = 1'b0;
  assign raw_dmem_read[3] = 1'b0;
  assign raw_dmem_read[4] = 1'b0;
  assign raw_dmem_read[5] = 1'b0;
  assign raw_dmem_read[6] = 1'b0;
  assign raw_dmem_read[7] = 1'b0;
  assign raw_dmem_read[8] = 1'b0;
  assign raw_dmem_read[9] = 1'b0;
  assign raw_dmem_read[10] = 1'b0;
  assign raw_dmem_read[11] = 1'b0;
  assign raw_dmem_read[12] = 1'b0;
  assign raw_dmem_read[13] = 1'b0;
  assign raw_dmem_read[14] = 1'b0;
  assign raw_dmem_read[15] = 1'b0;
  assign raw_dmem_read[16] = 1'b0;
  assign raw_dmem_read[17] = 1'b0;
  assign raw_dmem_read[18] = 1'b0;
  assign raw_dmem_read[19] = 1'b0;
  assign raw_dmem_read[20] = 1'b0;
  assign raw_dmem_read[21] = 1'b0;
  assign raw_dmem_read[22] = 1'b0;
  assign raw_dmem_read[23] = 1'b0;
  assign raw_dmem_read[24] = 1'b0;
  assign raw_dmem_read[25] = 1'b0;
  assign raw_dmem_read[26] = 1'b0;
  assign raw_dmem_read[27] = 1'b0;
  assign raw_dmem_read[28] = 1'b0;
  assign raw_dmem_read[29] = 1'b0;
  assign raw_dmem_read[30] = 1'b0;
  assign raw_dmem_read[31] = 1'b0;
  assign mem_write = 1'b0;
  assign mem_read = 1'b0;
  assign dmem_write_mask[0] = 1'b1;
  assign dmem_write_mask[1] = 1'b0;
  assign dmem_write_mask[2] = 1'b0;
  assign dmem_write_mask[3] = 1'b0;
  assign formatted_dmem_write[0] = 1'b0;
  assign formatted_dmem_write[1] = 1'b0;
  assign formatted_dmem_write[2] = 1'b0;
  assign formatted_dmem_write[3] = 1'b0;
  assign formatted_dmem_write[4] = 1'b0;
  assign formatted_dmem_write[5] = 1'b0;
  assign formatted_dmem_write[6] = 1'b0;
  assign formatted_dmem_write[7] = 1'b0;
  assign formatted_dmem_write[8] = 1'b0;
  assign formatted_dmem_write[9] = 1'b0;
  assign formatted_dmem_write[10] = 1'b0;
  assign formatted_dmem_write[11] = 1'b0;
  assign formatted_dmem_write[12] = 1'b0;
  assign formatted_dmem_write[13] = 1'b0;
  assign formatted_dmem_write[14] = 1'b0;
  assign formatted_dmem_write[15] = 1'b0;
  assign formatted_dmem_write[16] = 1'b0;
  assign formatted_dmem_write[17] = 1'b0;
  assign formatted_dmem_write[18] = 1'b0;
  assign formatted_dmem_write[19] = 1'b0;
  assign formatted_dmem_write[20] = 1'b0;
  assign formatted_dmem_write[21] = 1'b0;
  assign formatted_dmem_write[22] = 1'b0;
  assign formatted_dmem_write[23] = 1'b0;
  assign formatted_dmem_write[24] = 1'b0;
  assign formatted_dmem_write[25] = 1'b0;
  assign formatted_dmem_write[26] = 1'b0;
  assign formatted_dmem_write[27] = 1'b0;
  assign formatted_dmem_write[28] = 1'b0;
  assign formatted_dmem_write[29] = 1'b0;
  assign formatted_dmem_write[30] = 1'b0;
  assign formatted_dmem_write[31] = 1'b0;
  assign alu_result[0] = 1'b0;
  assign alu_result[1] = 1'b0;
  assign alu_result[2] = 1'b0;
  assign alu_result[3] = 1'b0;
  assign alu_result[4] = 1'b0;
  assign alu_result[5] = 1'b0;
  assign alu_result[6] = 1'b0;
  assign alu_result[7] = 1'b0;
  assign alu_result[8] = 1'b0;
  assign alu_result[9] = 1'b0;
  assign alu_result[10] = 1'b0;
  assign alu_result[11] = 1'b0;
  assign alu_result[12] = 1'b0;
  assign alu_result[13] = 1'b0;
  assign alu_result[14] = 1'b0;
  assign alu_result[15] = 1'b0;
  assign alu_result[16] = 1'b0;
  assign alu_result[17] = 1'b0;
  assign alu_result[18] = 1'b0;
  assign alu_result[19] = 1'b0;
  assign alu_result[20] = 1'b0;
  assign alu_result[21] = 1'b0;
  assign alu_result[22] = 1'b0;
  assign alu_result[23] = 1'b0;
  assign alu_result[24] = 1'b0;
  assign alu_result[25] = 1'b0;
  assign alu_result[26] = 1'b0;
  assign alu_result[27] = 1'b0;
  assign alu_result[28] = 1'b0;
  assign alu_result[29] = 1'b0;
  assign alu_result[30] = 1'b0;
  assign alu_result[31] = 1'b0;
  assign pc_current[0] = 1'b0;
  assign pc_current[1] = 1'b0;
  DFCNQD1 \riscv_core_inst_pc_inst_pc_reg[7] (.CDN (n_1), .CP (clk), .D
       (riscv_core_inst_pc_next[7]), .Q (pc_current[7]));
  DFCNQD1 \riscv_core_inst_pc_inst_pc_reg[3] (.CDN (n_1), .CP (clk), .D
       (riscv_core_inst_pc_next[3]), .Q (pc_current[3]));
  DFCNQD1 \riscv_core_inst_pc_inst_pc_reg[30] (.CDN (n_1), .CP (clk),
       .D (riscv_core_inst_pc_next[30]), .Q (pc_current[30]));
  DFCNQD1 \riscv_core_inst_pc_inst_pc_reg[4] (.CDN (n_1), .CP (clk), .D
       (riscv_core_inst_pc_next[4]), .Q (pc_current[4]));
  DFCNQD1 \riscv_core_inst_pc_inst_pc_reg[5] (.CDN (n_1), .CP (clk), .D
       (riscv_core_inst_pc_next[5]), .Q (pc_current[5]));
  DFCNQD1 \riscv_core_inst_pc_inst_pc_reg[6] (.CDN (n_1), .CP (clk), .D
       (riscv_core_inst_pc_next[6]), .Q (pc_current[6]));
  DFCNQD1 \riscv_core_inst_pc_inst_pc_reg[26] (.CDN (n_1), .CP (clk),
       .D (riscv_core_inst_pc_next[26]), .Q (pc_current[26]));
  DFCNQD1 \riscv_core_inst_pc_inst_pc_reg[14] (.CDN (n_1), .CP (clk),
       .D (riscv_core_inst_pc_next[14]), .Q (pc_current[14]));
  DFCNQD1 \riscv_core_inst_pc_inst_pc_reg[8] (.CDN (n_1), .CP (clk), .D
       (riscv_core_inst_pc_next[8]), .Q (pc_current[8]));
  DFCNQD1 \riscv_core_inst_pc_inst_pc_reg[9] (.CDN (n_1), .CP (clk), .D
       (riscv_core_inst_pc_next[9]), .Q (pc_current[9]));
  DFCNQD1 \riscv_core_inst_pc_inst_pc_reg[10] (.CDN (n_1), .CP (clk),
       .D (riscv_core_inst_pc_next[10]), .Q (pc_current[10]));
  DFCNQD1 \riscv_core_inst_pc_inst_pc_reg[11] (.CDN (n_1), .CP (clk),
       .D (riscv_core_inst_pc_next[11]), .Q (pc_current[11]));
  DFCNQD1 \riscv_core_inst_pc_inst_pc_reg[12] (.CDN (n_1), .CP (clk),
       .D (riscv_core_inst_pc_next[12]), .Q (pc_current[12]));
  DFCNQD1 \riscv_core_inst_pc_inst_pc_reg[13] (.CDN (n_1), .CP (clk),
       .D (riscv_core_inst_pc_next[13]), .Q (pc_current[13]));
  DFCNQD1 \riscv_core_inst_pc_inst_pc_reg[22] (.CDN (n_1), .CP (clk),
       .D (riscv_core_inst_pc_next[22]), .Q (pc_current[22]));
  DFCNQD1 \riscv_core_inst_pc_inst_pc_reg[16] (.CDN (n_1), .CP (clk),
       .D (riscv_core_inst_pc_next[16]), .Q (pc_current[16]));
  DFCNQD1 \riscv_core_inst_pc_inst_pc_reg[17] (.CDN (n_1), .CP (clk),
       .D (riscv_core_inst_pc_next[17]), .Q (pc_current[17]));
  DFCNQD1 \riscv_core_inst_pc_inst_pc_reg[18] (.CDN (n_1), .CP (clk),
       .D (riscv_core_inst_pc_next[18]), .Q (pc_current[18]));
  DFCNQD1 \riscv_core_inst_pc_inst_pc_reg[19] (.CDN (n_1), .CP (clk),
       .D (riscv_core_inst_pc_next[19]), .Q (pc_current[19]));
  DFCNQD1 \riscv_core_inst_pc_inst_pc_reg[20] (.CDN (n_1), .CP (clk),
       .D (riscv_core_inst_pc_next[20]), .Q (pc_current[20]));
  DFCNQD1 \riscv_core_inst_pc_inst_pc_reg[21] (.CDN (n_1), .CP (clk),
       .D (riscv_core_inst_pc_next[21]), .Q (pc_current[21]));
  DFCNQD1 \riscv_core_inst_pc_inst_pc_reg[15] (.CDN (n_1), .CP (clk),
       .D (riscv_core_inst_pc_next[15]), .Q (pc_current[15]));
  DFCNQD1 \riscv_core_inst_pc_inst_pc_reg[23] (.CDN (n_1), .CP (clk),
       .D (riscv_core_inst_pc_next[23]), .Q (pc_current[23]));
  DFCNQD1 \riscv_core_inst_pc_inst_pc_reg[24] (.CDN (n_1), .CP (clk),
       .D (riscv_core_inst_pc_next[24]), .Q (pc_current[24]));
  DFCNQD1 \riscv_core_inst_pc_inst_pc_reg[25] (.CDN (n_1), .CP (clk),
       .D (riscv_core_inst_pc_next[25]), .Q (pc_current[25]));
  DFCNQD1 \riscv_core_inst_pc_inst_pc_reg[27] (.CDN (n_1), .CP (clk),
       .D (riscv_core_inst_pc_next[27]), .Q (pc_current[27]));
  DFCNQD1 \riscv_core_inst_pc_inst_pc_reg[28] (.CDN (n_1), .CP (clk),
       .D (riscv_core_inst_pc_next[28]), .Q (pc_current[28]));
  DFCNQD1 \riscv_core_inst_pc_inst_pc_reg[29] (.CDN (n_1), .CP (clk),
       .D (riscv_core_inst_pc_next[29]), .Q (pc_current[29]));
  DFCNQD1 \riscv_core_inst_pc_inst_pc_reg[31] (.CDN (n_1), .CP (clk),
       .D (riscv_core_inst_pc_next[31]), .Q (pc_current[31]));
  CKND1 g254361(.I (rst), .ZN (n_1));
  XOR2D1 riscv_core_inst_add_57_83_g1367__2398(.A1
       (riscv_core_inst_add_57_83_n_872), .A2 (pc_current[27]), .Z
       (riscv_core_inst_pc_next[27]));
  XOR2D1 riscv_core_inst_add_57_83_g1368__5107(.A1
       (riscv_core_inst_add_57_83_n_876), .A2 (pc_current[23]), .Z
       (riscv_core_inst_pc_next[23]));
  HA1D0 riscv_core_inst_add_57_83_g1369__6260(.A (pc_current[26]), .B
       (riscv_core_inst_add_57_83_n_885), .CO
       (riscv_core_inst_add_57_83_n_872), .S
       (riscv_core_inst_pc_next[26]));
  XOR2D1 riscv_core_inst_add_57_83_g1370__4319(.A1
       (riscv_core_inst_add_57_83_n_880), .A2 (pc_current[19]), .Z
       (riscv_core_inst_pc_next[19]));
  XOR2D1 riscv_core_inst_add_57_83_g1371__8428(.A1
       (riscv_core_inst_add_57_83_n_882), .A2 (pc_current[15]), .Z
       (riscv_core_inst_pc_next[15]));
  HA1D0 riscv_core_inst_add_57_83_g1372__5526(.A (pc_current[22]), .B
       (riscv_core_inst_add_57_83_n_892), .CO
       (riscv_core_inst_add_57_83_n_876), .S
       (riscv_core_inst_pc_next[22]));
  XOR2D1 riscv_core_inst_add_57_83_g1373__6783(.A1
       (riscv_core_inst_add_57_83_n_887), .A2 (pc_current[11]), .Z
       (riscv_core_inst_pc_next[11]));
  XOR2D1 riscv_core_inst_add_57_83_g1374__3680(.A1
       (riscv_core_inst_add_57_83_n_889), .A2 (pc_current[30]), .Z
       (riscv_core_inst_pc_next[30]));
  HA1D0 riscv_core_inst_add_57_83_g1375__1617(.A (pc_current[18]), .B
       (riscv_core_inst_add_57_83_n_896), .CO
       (riscv_core_inst_add_57_83_n_880), .S
       (riscv_core_inst_pc_next[18]));
  HA1D0 riscv_core_inst_add_57_83_g1376__2802(.A (pc_current[14]), .B
       (riscv_core_inst_add_57_83_n_898), .CO
       (riscv_core_inst_add_57_83_n_882), .S
       (riscv_core_inst_pc_next[14]));
  XOR2D1 riscv_core_inst_add_57_83_g1377__1705(.A1
       (riscv_core_inst_add_57_83_n_894), .A2 (pc_current[7]), .Z
       (riscv_core_inst_pc_next[7]));
  HA1D0 riscv_core_inst_add_57_83_g1378__5122(.A (pc_current[25]), .B
       (riscv_core_inst_add_57_83_n_906), .CO
       (riscv_core_inst_add_57_83_n_885), .S
       (riscv_core_inst_pc_next[25]));
  HA1D0 riscv_core_inst_add_57_83_g1379__8246(.A (pc_current[10]), .B
       (riscv_core_inst_add_57_83_n_904), .CO
       (riscv_core_inst_add_57_83_n_887), .S
       (riscv_core_inst_pc_next[10]));
  HA1D0 riscv_core_inst_add_57_83_g1380__7098(.A (pc_current[29]), .B
       (riscv_core_inst_add_57_83_n_907), .CO
       (riscv_core_inst_add_57_83_n_889), .S
       (riscv_core_inst_pc_next[29]));
  XNR2D1 riscv_core_inst_add_57_83_g1381__6131(.A1
       (riscv_core_inst_add_57_83_n_899), .A2 (pc_current[31]), .ZN
       (riscv_core_inst_pc_next[31]));
  HA1D0 riscv_core_inst_add_57_83_g1382__1881(.A (pc_current[21]), .B
       (riscv_core_inst_add_57_83_n_912), .CO
       (riscv_core_inst_add_57_83_n_892), .S
       (riscv_core_inst_pc_next[21]));
  HA1D0 riscv_core_inst_add_57_83_g1383__5115(.A (pc_current[6]), .B
       (riscv_core_inst_add_57_83_n_910), .CO
       (riscv_core_inst_add_57_83_n_894), .S
       (riscv_core_inst_pc_next[6]));
  HA1D0 riscv_core_inst_add_57_83_g1384__7482(.A (pc_current[17]), .B
       (riscv_core_inst_add_57_83_n_916), .CO
       (riscv_core_inst_add_57_83_n_896), .S
       (riscv_core_inst_pc_next[17]));
  HA1D0 riscv_core_inst_add_57_83_g1385__4733(.A (pc_current[13]), .B
       (riscv_core_inst_add_57_83_n_914), .CO
       (riscv_core_inst_add_57_83_n_898), .S
       (riscv_core_inst_pc_next[13]));
  ND3D1 riscv_core_inst_add_57_83_g1386__6161(.A1
       (riscv_core_inst_add_57_83_n_907), .A2 (pc_current[29]), .A3
       (pc_current[30]), .ZN (riscv_core_inst_add_57_83_n_899));
  HA1D0 riscv_core_inst_add_57_83_g1387__9315(.A (pc_current[9]), .B
       (riscv_core_inst_add_57_83_n_918), .CO
       (riscv_core_inst_add_57_83_n_904), .S
       (riscv_core_inst_pc_next[9]));
  HA1D0 riscv_core_inst_add_57_83_g1388__9945(.A (pc_current[24]), .B
       (riscv_core_inst_add_57_83_n_919), .CO
       (riscv_core_inst_add_57_83_n_906), .S
       (riscv_core_inst_pc_next[24]));
  HA1D0 riscv_core_inst_add_57_83_g1389__2883(.A (pc_current[28]), .B
       (riscv_core_inst_add_57_83_n_921), .CO
       (riscv_core_inst_add_57_83_n_907), .S
       (riscv_core_inst_pc_next[28]));
  HA1D0 riscv_core_inst_add_57_83_g1390__2346(.A (pc_current[5]), .B
       (riscv_core_inst_add_57_83_n_926), .CO
       (riscv_core_inst_add_57_83_n_910), .S
       (riscv_core_inst_pc_next[5]));
  HA1D0 riscv_core_inst_add_57_83_g1391__1666(.A (pc_current[20]), .B
       (riscv_core_inst_add_57_83_n_927), .CO
       (riscv_core_inst_add_57_83_n_912), .S
       (riscv_core_inst_pc_next[20]));
  HA1D0 riscv_core_inst_add_57_83_g1392__7410(.A (pc_current[12]), .B
       (riscv_core_inst_add_57_83_n_933), .CO
       (riscv_core_inst_add_57_83_n_914), .S
       (riscv_core_inst_pc_next[12]));
  HA1D0 riscv_core_inst_add_57_83_g1393__6417(.A (pc_current[16]), .B
       (riscv_core_inst_add_57_83_n_935), .CO
       (riscv_core_inst_add_57_83_n_916), .S
       (riscv_core_inst_pc_next[16]));
  HA1D0 riscv_core_inst_add_57_83_g1394__5477(.A (pc_current[8]), .B
       (riscv_core_inst_add_57_83_n_937), .CO
       (riscv_core_inst_add_57_83_n_918), .S
       (riscv_core_inst_pc_next[8]));
  INR2XD0 riscv_core_inst_add_57_83_g1395__2398(.A1
       (riscv_core_inst_add_57_83_n_927), .B1
       (riscv_core_inst_add_57_83_n_948), .ZN
       (riscv_core_inst_add_57_83_n_919));
  AN4XD1 riscv_core_inst_add_57_83_g1396__5107(.A1
       (riscv_core_inst_add_57_83_n_928), .A2
       (riscv_core_inst_add_57_83_n_935), .A3 (pc_current[25]), .A4
       (pc_current[24]), .Z (riscv_core_inst_add_57_83_n_921));
  HA1D0 riscv_core_inst_add_57_83_g1397__6260(.A (pc_current[4]), .B
       (riscv_core_inst_add_57_83_n_941), .CO
       (riscv_core_inst_add_57_83_n_926), .S
       (riscv_core_inst_pc_next[4]));
  INR2XD0 riscv_core_inst_add_57_83_g1398__4319(.A1
       (riscv_core_inst_add_57_83_n_935), .B1
       (riscv_core_inst_add_57_83_n_953), .ZN
       (riscv_core_inst_add_57_83_n_927));
  IINR4D0 riscv_core_inst_add_57_83_g1399__8428(.A1 (pc_current[27]),
       .A2 (pc_current[26]), .B1 (riscv_core_inst_add_57_83_n_948), .B2
       (riscv_core_inst_add_57_83_n_953), .ZN
       (riscv_core_inst_add_57_83_n_928));
  INR2XD0 riscv_core_inst_add_57_83_g1400__5526(.A1
       (riscv_core_inst_add_57_83_n_937), .B1
       (riscv_core_inst_add_57_83_n_958), .ZN
       (riscv_core_inst_add_57_83_n_933));
  INR3D0 riscv_core_inst_add_57_83_g1401__6783(.A1
       (riscv_core_inst_add_57_83_n_937), .B1
       (riscv_core_inst_add_57_83_n_958), .B2
       (riscv_core_inst_add_57_83_n_943), .ZN
       (riscv_core_inst_add_57_83_n_935));
  AN4XD1 riscv_core_inst_add_57_83_g1402__3680(.A1
       (riscv_core_inst_add_57_83_n_941), .A2
       (riscv_core_inst_add_57_83_n_963), .A3 (pc_current[5]), .A4
       (pc_current[4]), .Z (riscv_core_inst_add_57_83_n_937));
  HA1D0 riscv_core_inst_add_57_83_g1403__1617(.A (pc_current[3]), .B
       (pc_current[2]), .CO (riscv_core_inst_add_57_83_n_941), .S
       (riscv_core_inst_pc_next[3]));
  ND4D1 riscv_core_inst_add_57_83_g1404__2802(.A1 (pc_current[13]), .A2
       (pc_current[12]), .A3 (pc_current[15]), .A4 (pc_current[14]),
       .ZN (riscv_core_inst_add_57_83_n_943));
  ND4D1 riscv_core_inst_add_57_83_g1405__1705(.A1 (pc_current[20]), .A2
       (pc_current[22]), .A3 (pc_current[23]), .A4 (pc_current[21]),
       .ZN (riscv_core_inst_add_57_83_n_948));
  ND4D1 riscv_core_inst_add_57_83_g1406__5122(.A1 (pc_current[17]), .A2
       (pc_current[16]), .A3 (pc_current[19]), .A4 (pc_current[18]),
       .ZN (riscv_core_inst_add_57_83_n_953));
  ND4D1 riscv_core_inst_add_57_83_g1407__8246(.A1 (pc_current[9]), .A2
       (pc_current[11]), .A3 (pc_current[10]), .A4 (pc_current[8]), .ZN
       (riscv_core_inst_add_57_83_n_958));
  AN2XD1 riscv_core_inst_add_57_83_g1408__7098(.A1 (pc_current[6]), .A2
       (pc_current[7]), .Z (riscv_core_inst_add_57_83_n_963));
  DFCND1 \riscv_core_inst_pc_inst_pc_reg[2] (.CDN (n_1), .CP (clk), .D
       (n_0), .Q (pc_current[2]), .QN (n_0));
endmodule

