
// Generated by Cadence Genus(TM) Synthesis Solution 21.18-s082_1
// Generated on: Jul 28 2026 07:00:33 EDT (Jul 28 2026 11:00:33 UTC)

// Verification Directory fv/counter 

module counter(clk, reset, count);
  input clk, reset;
  output [3:0] count;
  wire clk, reset;
  wire [3:0] count;
  wire inc_add_13_28_n_35, inc_add_13_28_n_40, n_0, n_1, n_3, n_4, n_5;
  DFCNQD1 \count_reg[1] (.CDN (n_0), .CP (clk), .D (n_5), .Q
       (count[1]));
  DFCNQD1 \count_reg[2] (.CDN (n_0), .CP (clk), .D (n_4), .Q
       (count[2]));
  DFCNQD1 \count_reg[3] (.CDN (n_0), .CP (clk), .D (n_3), .Q
       (count[3]));
  INVD1 g13(.I (reset), .ZN (n_0));
  MOAI22D1 inc_add_13_28_g38__2398(.A1 (inc_add_13_28_n_35), .A2
       (count[3]), .B1 (inc_add_13_28_n_35), .B2 (count[3]), .ZN (n_3));
  OA21D1 inc_add_13_28_g39__5107(.A1 (inc_add_13_28_n_40), .A2
       (count[2]), .B (inc_add_13_28_n_35), .Z (n_4));
  ND2D1 inc_add_13_28_g40__6260(.A1 (inc_add_13_28_n_40), .A2
       (count[2]), .ZN (inc_add_13_28_n_35));
  IAO21D1 inc_add_13_28_g41__4319(.A1 (count[0]), .A2 (count[1]), .B
       (inc_add_13_28_n_40), .ZN (n_5));
  AN2XD1 inc_add_13_28_g42__8428(.A1 (count[0]), .A2 (count[1]), .Z
       (inc_add_13_28_n_40));
  DFCND1 \count_reg[0] (.CDN (n_0), .CP (clk), .D (n_1), .Q (count[0]),
       .QN (n_1));
endmodule

