
// Generated by Cadence Genus(TM) Synthesis Solution 21.18-s082_1
// Generated on: Jul 30 2026 08:05:27 EDT (Jul 30 2026 12:05:27 UTC)

// Verification Directory fv/counter 

module counter(clk, reset, count);
  input clk, reset;
  output [3:0] count;
  wire clk, reset;
  wire [3:0] count;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6;
  EDFCNQD4 \count_reg[3] (.CDN (n_6), .CP (clk), .D (n_1), .E (n_4), .Q
       (count[3]));
  DFCNQD4 \count_reg[2] (.CDN (n_6), .CP (clk), .D (n_5), .Q
       (count[2]));
  HA1D0 g82__2398(.A (count[2]), .B (n_2), .CO (n_4), .S (n_5));
  DFCNQD4 \count_reg[1] (.CDN (n_6), .CP (clk), .D (n_3), .Q
       (count[1]));
  HA1D0 g84__5107(.A (count[0]), .B (count[1]), .CO (n_2), .S (n_3));
  DFCNQD4 \count_reg[0] (.CDN (n_6), .CP (clk), .D (n_0), .Q
       (count[0]));
  INVD1 g86(.I (count[3]), .ZN (n_1));
  INVD1 g88(.I (count[0]), .ZN (n_0));
  CKND0 g87(.I (reset), .ZN (n_6));
endmodule

