
// Generated by Cadence Genus(TM) Synthesis Solution 21.18-s082_1
// Generated on: Jul 30 2026 06:56:14 EDT (Jul 30 2026 10:56:14 UTC)

// Verification Directory fv/counter 

module counter(clk, reset, count, SE, scan_in, scan_out);
  input clk, reset, SE, scan_in;
  output [3:0] count;
  output scan_out;
  wire clk, reset, SE, scan_in;
  wire [3:0] count;
  wire scan_out;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6;
  assign scan_out = count[3];
  SDFCNQD1 \count_reg[3] (.CDN (n_6), .CP (clk), .D (n_5), .SI
       (count[2]), .SE (SE), .Q (count[3]));
  SDFCNQD1 \count_reg[2] (.CDN (n_6), .CP (clk), .D (n_4), .SI
       (count[1]), .SE (SE), .Q (count[2]));
  CKXOR2D1 g81__2398(.A1 (n_3), .A2 (count[3]), .Z (n_5));
  HA1D0 g83__5107(.A (count[2]), .B (n_1), .CO (n_3), .S (n_4));
  SDFCNQD1 \count_reg[1] (.CDN (n_6), .CP (clk), .D (n_2), .SI
       (count[0]), .SE (SE), .Q (count[1]));
  SDFCNQD1 \count_reg[0] (.CDN (n_6), .CP (clk), .D (n_0), .SI
       (scan_in), .SE (SE), .Q (count[0]));
  HA1D0 g85__6260(.A (count[0]), .B (count[1]), .CO (n_1), .S (n_2));
  CKND0 g87(.I (reset), .ZN (n_6));
  INVD1 g88(.I (count[0]), .ZN (n_0));
endmodule

