
// Generated by Cadence Genus(TM) Synthesis Solution 21.18-s082_1
// Generated on: Jul 29 2026 05:32:09 EDT (Jul 29 2026 09:32:09 UTC)

// Verification Directory fv/counter 

module counter(clk, reset, count);
  input clk, reset;
  output [3:0] count;
  wire clk, reset;
  wire [3:0] count;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6;
  DFCNQD1 \count_reg[3] (.CDN (n_5), .CP (clk), .D (n_6), .Q
       (count[3]));
  XOR2D1 g81__2398(.A1 (n_3), .A2 (count[3]), .Z (n_6));
  DFCNQD1 \count_reg[2] (.CDN (n_5), .CP (clk), .D (n_4), .Q
       (count[2]));
  HA1D0 g83__5107(.A (count[2]), .B (n_1), .CO (n_3), .S (n_4));
  DFCNQD1 \count_reg[1] (.CDN (n_5), .CP (clk), .D (n_2), .Q
       (count[1]));
  HA1D0 g85__6260(.A (count[0]), .B (count[1]), .CO (n_1), .S (n_2));
  CKND0 g87(.I (reset), .ZN (n_5));
  DFCND1 \count_reg[0] (.CDN (n_5), .CP (clk), .D (n_0), .Q (count[0]),
       .QN (n_0));
endmodule

