
// Generated by Cadence Genus(TM) Synthesis Solution 21.18-s082_1
// Generated on: Jul 30 2026 07:53:01 EDT (Jul 30 2026 11:53:01 UTC)

// Verification Directory fv/counter 

module counter(clk, reset, count);
  input clk, reset;
  output [3:0] count;
  wire clk, reset;
  wire [3:0] count;
  wire n_3, n_4, n_5, n_6, n_7, n_8, n_9;
  DFCNQD1 \count_reg[3] (.CDN (n_8), .CP (clk), .D (n_9), .Q
       (count[3]));
  XOR2D1 g81__2398(.A1 (n_6), .A2 (count[3]), .Z (n_9));
  DFCNQD1 \count_reg[2] (.CDN (n_8), .CP (clk), .D (n_7), .Q
       (count[2]));
  HA1D0 g83__5107(.A (count[2]), .B (n_4), .CO (n_6), .S (n_7));
  DFCNQD1 \count_reg[1] (.CDN (n_8), .CP (clk), .D (n_5), .Q
       (count[1]));
  HA1D0 g85__6260(.A (count[0]), .B (count[1]), .CO (n_4), .S (n_5));
  CKND0 g89(.I (reset), .ZN (n_8));
  DFCND1 \count_reg[0] (.CDN (n_8), .CP (clk), .D (n_3), .Q (count[0]),
       .QN (n_3));
endmodule

