
// Generated by Cadence Genus(TM) Synthesis Solution 21.18-s082_1
// Generated on: Jul 29 2026 05:30:26 EDT (Jul 29 2026 09:30:26 UTC)

// Verification Directory fv/counter 

module counter(clk, reset, count);
  input clk, reset;
  output [3:0] count;
  wire clk, reset;
  wire [3:0] count;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6;
  DFCNQD1 \count_reg[3] (.CDN (n_6), .CP (clk), .D (n_5), .Q
       (count[3]));
  DFCNQD1 \count_reg[2] (.CDN (n_6), .CP (clk), .D (n_3), .Q
       (count[2]));
  MOAI22D1 g81__2398(.A1 (n_4), .A2 (count[3]), .B1 (n_4), .B2
       (count[3]), .ZN (n_5));
  DFCNQD1 \count_reg[1] (.CDN (n_6), .CP (clk), .D (n_1), .Q
       (count[1]));
  OA21D1 g83__5107(.A1 (n_2), .A2 (count[2]), .B (n_4), .Z (n_3));
  ND2D1 g85__6260(.A1 (n_2), .A2 (count[2]), .ZN (n_4));
  IAO21D1 g86__4319(.A1 (count[0]), .A2 (count[1]), .B (n_2), .ZN
       (n_1));
  AN2XD1 g88__8428(.A1 (count[0]), .A2 (count[1]), .Z (n_2));
  CKND0 g89(.I (reset), .ZN (n_6));
  DFCND1 \count_reg[0] (.CDN (n_6), .CP (clk), .D (n_0), .Q (count[0]),
       .QN (n_0));
endmodule

