
// Generated by Cadence Genus(TM) Synthesis Solution 21.18-s082_1
// Generated on: Jul 28 2026 06:54:08 EDT (Jul 28 2026 10:54:08 UTC)

// Verification Directory fv/counter 

module counter(clk, reset, count);
  input clk, reset;
  output [3:0] count;
  wire clk, reset;
  wire [3:0] count;
  wire n_0, n_3, n_4, n_5, n_6, n_9, n_10, n_14;
  wire n_15;
  SDFCNQD4 \count_reg[3] (.CDN (n_6), .CP (clk), .D (n_0), .SI
       (count[3]), .SE (n_5), .Q (count[3]));
  SDFCNQD4 \count_reg[2] (.CDN (n_6), .CP (clk), .D (n_3), .SI
       (count[2]), .SE (n_4), .Q (count[2]));
  OR2XD1 g83__2398(.A1 (n_4), .A2 (n_3), .Z (n_5));
  CKND2D0 g85__5107(.A1 (n_10), .A2 (count[1]), .ZN (n_4));
  INVD0 g86(.I (count[3]), .ZN (n_0));
  INVD0 g88(.I (count[2]), .ZN (n_3));
  CKND0 g89(.I (reset), .ZN (n_6));
  DFCND4 \count_reg[0] (.CDN (n_6), .CP (clk), .D (n_9), .Q (count[0]),
       .QN (n_9));
  CKND1 fopt1(.I (n_9), .ZN (n_10));
  SDFCNQD4 \count_reg[1] (.CDN (n_6), .CP (clk), .D (n_14), .SI (n_15),
       .SE (n_10), .Q (count[1]));
  INVD0 fopt116(.I (n_15), .ZN (n_14));
  INVD0 fopt117(.I (count[1]), .ZN (n_15));
endmodule

