
// Generated by Cadence Genus(TM) Synthesis Solution 21.18-s082_1
// Generated on: Aug 11 2026 02:56:24 EDT (Aug 11 2026 06:56:24 UTC)

// Verification Directory fv/top_wrapper 

module top_wrapper(A, B, Sel, clk_in, rst, Out);
  input [7:0] A, B;
  input [1:0] Sel;
  input clk_in, rst;
  output [7:0] Out;
  wire [7:0] A, B;
  wire [1:0] Sel;
  wire clk_in, rst;
  wire [7:0] Out;
  wire [7:0] wA;
  wire [7:0] wB;
  wire [7:0] wOut;
  wire [1:0] wSel;
  wire UNCONNECTED, UNCONNECTED0, UNCONNECTED1, UNCONNECTED2,
       UNCONNECTED3, UNCONNECTED4, UNCONNECTED5, UNCONNECTED6;
  wire UNCONNECTED7, n_0, n_1, n_2, n_3, n_4, n_5, n_6;
  wire n_7, n_8, n_9, n_10, n_11, n_12, n_13, n_14;
  wire n_15, n_16, n_17, n_18, n_19, n_20, n_21, n_22;
  wire n_23, n_24, n_25, n_26, n_27, n_28, n_29, n_30;
  wire n_31, n_32, n_33, n_34, n_35, wclk, wrst;
  PDDW16DGZ A_inst0(.REN (1'b1), .I (1'b1), .OEN (1'b1), .PAD (A[0]),
       .C (wA[0]));
  PDDW16DGZ A_inst1(.REN (1'b1), .I (1'b1), .OEN (1'b1), .PAD (A[1]),
       .C (wA[1]));
  PDDW16DGZ A_inst2(.REN (1'b1), .I (1'b1), .OEN (1'b1), .PAD (A[2]),
       .C (wA[2]));
  PDDW16DGZ A_inst3(.REN (1'b1), .I (1'b1), .OEN (1'b1), .PAD (A[3]),
       .C (wA[3]));
  PDDW16DGZ A_inst4(.REN (1'b1), .I (1'b1), .OEN (1'b1), .PAD (A[4]),
       .C (wA[4]));
  PDDW16DGZ A_inst5(.REN (1'b1), .I (1'b1), .OEN (1'b1), .PAD (A[5]),
       .C (wA[5]));
  PDDW16DGZ A_inst6(.REN (1'b1), .I (1'b1), .OEN (1'b1), .PAD (A[6]),
       .C (wA[6]));
  PDDW16DGZ A_inst7(.REN (1'b1), .I (1'b1), .OEN (1'b1), .PAD (A[7]),
       .C (wA[7]));
  PDDW16DGZ B_inst0(.REN (1'b1), .I (1'b1), .OEN (1'b1), .PAD (B[0]),
       .C (wB[0]));
  PDDW16DGZ B_inst1(.REN (1'b1), .I (1'b1), .OEN (1'b1), .PAD (B[1]),
       .C (wB[1]));
  PDDW16DGZ B_inst2(.REN (1'b1), .I (1'b1), .OEN (1'b1), .PAD (B[2]),
       .C (wB[2]));
  PDDW16DGZ B_inst3(.REN (1'b1), .I (1'b1), .OEN (1'b1), .PAD (B[3]),
       .C (wB[3]));
  PDDW16DGZ B_inst4(.REN (1'b1), .I (1'b1), .OEN (1'b1), .PAD (B[4]),
       .C (wB[4]));
  PDDW16DGZ B_inst5(.REN (1'b1), .I (1'b1), .OEN (1'b1), .PAD (B[5]),
       .C (wB[5]));
  PDDW16DGZ B_inst6(.REN (1'b1), .I (1'b1), .OEN (1'b1), .PAD (B[6]),
       .C (wB[6]));
  PDDW16DGZ B_inst7(.REN (1'b1), .I (1'b1), .OEN (1'b1), .PAD (B[7]),
       .C (wB[7]));
  PDXOE3DG clk_pad(.XIN (clk_in), .E (1'b1), .XOUT (UNCONNECTED), .XC
       (wclk));
  PDDW16DGZ out_inst0(.REN (1'b0), .I (wOut[0]), .OEN (1'b0), .PAD
       (Out[0]), .C (UNCONNECTED0));
  PDDW16DGZ out_inst1(.REN (1'b0), .I (wOut[1]), .OEN (1'b0), .PAD
       (Out[1]), .C (UNCONNECTED1));
  PDDW16DGZ out_inst2(.REN (1'b0), .I (wOut[2]), .OEN (1'b0), .PAD
       (Out[2]), .C (UNCONNECTED2));
  PDDW16DGZ out_inst3(.REN (1'b0), .I (wOut[3]), .OEN (1'b0), .PAD
       (Out[3]), .C (UNCONNECTED3));
  PDDW16DGZ out_inst4(.REN (1'b0), .I (wOut[4]), .OEN (1'b0), .PAD
       (Out[4]), .C (UNCONNECTED4));
  PDDW16DGZ out_inst5(.REN (1'b0), .I (wOut[5]), .OEN (1'b0), .PAD
       (Out[5]), .C (UNCONNECTED5));
  PDDW16DGZ out_inst6(.REN (1'b0), .I (wOut[6]), .OEN (1'b0), .PAD
       (Out[6]), .C (UNCONNECTED6));
  PDDW16DGZ out_inst7(.REN (1'b0), .I (wOut[7]), .OEN (1'b0), .PAD
       (Out[7]), .C (UNCONNECTED7));
  PDDW16DGZ rst_inst(.REN (1'b1), .I (1'b1), .OEN (1'b1), .PAD (rst),
       .C (wrst));
  PDDW16DGZ sel_inst0(.REN (1'b1), .I (1'b1), .OEN (1'b1), .PAD
       (Sel[0]), .C (wSel[0]));
  PDDW16DGZ sel_inst1(.REN (1'b1), .I (1'b1), .OEN (1'b1), .PAD
       (Sel[1]), .C (wSel[1]));
  DFQD4 \u_alu_core_Out_reg[3] (.CP (wclk), .D (n_28), .Q (wOut[3]));
  DFQD4 \u_alu_core_Out_reg[1] (.CP (wclk), .D (n_35), .Q (wOut[1]));
  DFQD4 \u_alu_core_Out_reg[0] (.CP (wclk), .D (n_31), .Q (wOut[0]));
  DFQD4 \u_alu_core_Out_reg[7] (.CP (wclk), .D (n_29), .Q (wOut[7]));
  DFQD4 \u_alu_core_Out_reg[5] (.CP (wclk), .D (n_34), .Q (wOut[5]));
  DFQD4 \u_alu_core_Out_reg[2] (.CP (wclk), .D (n_30), .Q (wOut[2]));
  DFQD4 \u_alu_core_Out_reg[4] (.CP (wclk), .D (n_33), .Q (wOut[4]));
  DFQD4 \u_alu_core_Out_reg[6] (.CP (wclk), .D (n_32), .Q (wOut[6]));
  OAI221D0 g978__2398(.A1 (n_11), .A2 (n_1), .B1 (wB[1]), .B2 (n_9), .C
       (n_21), .ZN (n_35));
  OAI221D0 g979__5107(.A1 (n_11), .A2 (n_2), .B1 (wB[5]), .B2 (n_9), .C
       (n_27), .ZN (n_34));
  OAI221D0 g980__6260(.A1 (n_11), .A2 (n_8), .B1 (wB[4]), .B2 (n_9), .C
       (n_26), .ZN (n_33));
  OAI221D0 g981__4319(.A1 (n_11), .A2 (n_0), .B1 (wB[6]), .B2 (n_9), .C
       (n_24), .ZN (n_32));
  OAI221D0 g982__8428(.A1 (n_11), .A2 (n_3), .B1 (wB[0]), .B2 (n_9), .C
       (n_20), .ZN (n_31));
  OAI221D0 g983__5526(.A1 (n_11), .A2 (n_5), .B1 (wB[2]), .B2 (n_9), .C
       (n_23), .ZN (n_30));
  OAI221D0 g984__6783(.A1 (n_11), .A2 (n_6), .B1 (wA[7]), .B2 (n_10),
       .C (n_22), .ZN (n_29));
  OAI221D0 g985__3680(.A1 (n_11), .A2 (n_7), .B1 (wA[3]), .B2 (n_10),
       .C (n_25), .ZN (n_28));
  AOI31D1 g986__1617(.A1 (n_4), .A2 (wB[5]), .A3 (wA[5]), .B (n_16),
       .ZN (n_27));
  AOI31D1 g987__2802(.A1 (n_4), .A2 (wB[4]), .A3 (wA[4]), .B (n_19),
       .ZN (n_26));
  AOI31D1 g988__1705(.A1 (n_4), .A2 (wA[3]), .A3 (wB[3]), .B (n_17),
       .ZN (n_25));
  AOI31D1 g989__5122(.A1 (n_4), .A2 (wB[6]), .A3 (wA[6]), .B (n_13),
       .ZN (n_24));
  AOI31D1 g990__8246(.A1 (n_4), .A2 (wB[2]), .A3 (wA[2]), .B (n_12),
       .ZN (n_23));
  AOI31D1 g991__7098(.A1 (n_4), .A2 (wA[7]), .A3 (wB[7]), .B (n_14),
       .ZN (n_22));
  AOI31D1 g992__6131(.A1 (n_4), .A2 (wB[1]), .A3 (wA[1]), .B (n_15),
       .ZN (n_21));
  AOI31D1 g993__1881(.A1 (n_4), .A2 (wB[0]), .A3 (wA[0]), .B (n_18),
       .ZN (n_20));
  NR2D1 g994__5115(.A1 (n_10), .A2 (wA[4]), .ZN (n_19));
  NR2D1 g995__7482(.A1 (n_10), .A2 (wA[0]), .ZN (n_18));
  NR2D1 g996__4733(.A1 (n_9), .A2 (wB[3]), .ZN (n_17));
  NR2D1 g997__6161(.A1 (n_10), .A2 (wA[5]), .ZN (n_16));
  NR2D1 g998__9315(.A1 (n_10), .A2 (wA[1]), .ZN (n_15));
  NR2D1 g999__9945(.A1 (n_9), .A2 (wB[7]), .ZN (n_14));
  NR2D1 g1000__2883(.A1 (n_10), .A2 (wA[6]), .ZN (n_13));
  NR2D1 g1001__2346(.A1 (n_10), .A2 (wA[2]), .ZN (n_12));
  ND2D1 g1002__1666(.A1 (n_4), .A2 (wSel[0]), .ZN (n_11));
  IND3D1 g1003__7410(.A1 (wSel[0]), .B1 (wSel[1]), .B2 (wrst), .ZN
       (n_10));
  ND3D1 g1004__6417(.A1 (wrst), .A2 (wSel[1]), .A3 (wSel[0]), .ZN
       (n_9));
  NR2D0 g1005__5477(.A1 (wB[4]), .A2 (wA[4]), .ZN (n_8));
  NR2D0 g1006__2398(.A1 (wA[3]), .A2 (wB[3]), .ZN (n_7));
  NR2D0 g1007__5107(.A1 (wA[7]), .A2 (wB[7]), .ZN (n_6));
  NR2D0 g1008__6260(.A1 (wB[2]), .A2 (wA[2]), .ZN (n_5));
  NR2D0 g1009__4319(.A1 (wB[0]), .A2 (wA[0]), .ZN (n_3));
  NR2D0 g1010__8428(.A1 (wB[5]), .A2 (wA[5]), .ZN (n_2));
  NR2D0 g1011__5526(.A1 (wB[1]), .A2 (wA[1]), .ZN (n_1));
  NR2D0 g1012__6783(.A1 (wB[6]), .A2 (wA[6]), .ZN (n_0));
  INR2D1 g1013__3680(.A1 (wrst), .B1 (wSel[1]), .ZN (n_4));
endmodule

